services:
  - type: web
    name: linkedin-agent
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/linkdeinAgent/browser
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: API_URL
        value: ''
        sync: false
      - key: NODE_ENV
        value: production
        sync: false

